import { FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { getComponents, getDatabase, getIncidents } from '../db/database.js';

export async function postMortemApiRoutes(fastify: FastifyInstance): Promise<void> {
  fastify.get(
    '/api/incidents/:id/post-mortem',
    async (
      request: FastifyRequest<{ Params: { id: string } }>,
      reply: FastifyReply
    ) => {
      const { id } = request.params;
      const db = getDatabase();

      const incRow = db
        .prepare('SELECT id, page_id, title, status, severity, created_at, resolved_at FROM incidents WHERE id = ?')
        .get(id) as any;

      if (!incRow) {
        return reply.code(404).send({ error: 'Incident not found' });
      }

      const incidents = getIncidents(incRow.page_id, 365);
      const incident = incidents.find((i) => i.id === id);
      if (!incident) {
        return reply.code(404).send({ error: 'Incident details not found' });
      }

      const allComponents = getComponents(incRow.page_id);
      const affectedNames = allComponents
        .filter((c) => incident.affectedComponentIds.includes(c.id))
        .map((c) => c.name);

      const createdDate = new Date(incident.createdAt);
      const resolvedDate = incident.resolvedAt ? new Date(incident.resolvedAt) : null;
      const durationMinutes = resolvedDate
        ? Math.max(1, Math.round((resolvedDate.getTime() - createdDate.getTime()) / 60000))
        : 'Ongoing';

      const timelineLines = incident.updates
        .map((u) => {
          const time = new Date(u.createdAt).toISOString();
          return `- **${time}** [${u.status}]: ${u.message}`;
        })
        .join('\n');

      const markdown = `
# Incident Post-Mortem: ${incident.title}

**Incident ID:** \`${incident.id}\`  
**Severity:** ${incident.severity}  
**Impacted Services:** ${affectedNames.join(', ') || 'Global'}  
**Total Duration:** ${typeof durationMinutes === 'number' ? `${durationMinutes} minutes` : durationMinutes}  
**Started:** ${createdDate.toUTCString()}  
**Resolved:** ${resolvedDate ? resolvedDate.toUTCString() : 'In Progress'}  

---

## 1. Executive Summary
On ${createdDate.toISOString().split('T')[0]}, an incident classified as **${incident.severity}** impacted **${affectedNames.join(', ') || 'core infrastructure'}**. 
The incident was detected at ${createdDate.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} UTC and full recovery was verified after ${durationMinutes} minutes.

## 2. Customer & Operational Impact
- **Impacted Components:** ${affectedNames.map((n) => `\`${n}\``).join(', ')}
- **Initial Observation:** ${incident.updates[0]?.message || 'Elevated error rates detected.'}
- **Availability Degradation:** Temporary performance reduction during active mitigation window.

## 3. Incident Timeline
${timelineLines || '- No updates recorded.'}

## 4. Root Cause & Remediation
- **Root Cause:** Initial telemetry identified anomalies in ${affectedNames.join(' and ') || 'the system'}.
- **Remediation Action:** ${incident.updates[incident.updates.length - 1]?.message || 'Remediation completed.'}

## 5. Preventative & Follow-Up Actions
- [x] Automated health pings verified operational thresholds.
- [ ] Review alert latency rules and configure tighter threshold monitors.
- [ ] Update failover playbooks and automated fallback circuits.

---
*Generated by StatusCast Autonomous Incident Engine on ${new Date().toUTCString()}*
`.trim();

      return reply.send({
        success: true,
        incidentId: id,
        markdown,
        durationMinutes,
      });
    }
  );
}
